### ISSUE TITLE
Buttons moving when the 'pi' replacement is done

### ISSUE THREAD

**Issue by raalraan** [kaer/gnome-shell-extension-modern-calc#1]
Hi, thanks for this great extension. In the current setup, the buttons below the entry space move when the text 'pi' is replaced by the character 'π' and move again when it is deleted. I suggest hardcoding a height for .calc-entry, for example, adding

.display-group .calc-entry {
   height:1.4em;
}

in stylesheet.css solves it for me

**Comment by kaer** [comment]
Thanks raalraan by opening this issue, I'll fix this problem in next release, I guess the font family should be changed too, when PI is inserted the font-weight or face of entire expression changes.

**Comment by raalraan** [comment]
Yes, that's true. I tested using a monospaced font and there is no need for the height tweak I mentioned, just adding 

.history-group .history-container,
.display-group .calc-entry {
    font-family:monospace;
}

prevents both height and font changing. I included ".history-group .history-container" because the font changing problem happens there too.

**Comment by kaer** [comment]
Thanks by the fix.

Actually I paused the development because I'm busy with some things and
later I'll implement a unit converter using this library
https://github.com/gentooboontoo/js-quantities .

2014-12-11 21:11 GMT-02:00 raalraan notifications@github.com:
