### ISSUE TITLE
Calc dialog is always open after login/screen unlock, on a multiple monitor setup

### ISSUE THREAD

**Issue by lonetwin** [kaer/gnome-shell-extension-modern-calc#2]
Hi,
Thanks for writing this extension, it's been useful. However, there's a small annoyance. Each time I login or if I step afk and return to unlock my system I see this on my dual-screen setup.

![single screenshot of my dual-screen setup -- left half is my primary display ](https://cloud.githubusercontent.com/assets/101819/5772615/4de45c76-9d90-11e4-9a63-2268bf4b9287.png)

...and I have to click on the calc icon on the taskbar, to have it show up on my current primary desktop (the left half in that screenshot) and then again to close it. 

I'm running gnome-shell-3.10.4-9.fc20.x86_64 on Fedora 20. I'm sorry I can't send in a pull request or even isolate the code that causes this behavior since I don't know much about g-s-extensions but can help with any debugging that you might need me to do.

**Comment by trailjeep** [comment]
Exact same issue here:
- Debian GNU/Linux 8.0 (jessie)
- Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.3 (Debian 4.8.3-16) ) #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08)
- GNOME Shell 3.14.2

I do love this extension and especially look forward to more conversion types!

**Comment by kaer** [comment]
Thanks by filling this issue, I'm not at my PC but I changed the code to prevent this bug https://github.com/kaer/gnome-shell-extension-modern-calc/commit/139da15c4172d360149d6fd1ff6a2b91423de3a0 , I don't have dual screen to test it, please can you test and give me a feedback?

**Comment by kaer** [comment]
Trailjeep more units were added, later it'll support customized units but first unit translation will come.

**Comment by trailjeep** [comment]
Same behavior as before - Initially open on second monitor (startup & unlock.)
Once closed, opens in correct area - right side of primary monitor.
Possible hint, when I enable reveal animation it starts on left side of secondary monitor then slides in to right side of primary.

New:  Icon in bar only opens, but no longer closes (I can tell it only opens with reveal animation on.)
Clicking anywhere on primary monitor closes.  Clicking anywhere on secondary monitor does not close.

BTW, I updated first, tested, then uninstalled and reinstalled with same effect.

Nice job with extra conversions I am hopeful for data units at some future time.

Any more testing I can do, just let me know.

**Comment by trailjeep** [comment]
I am not a dev, but from what I'm seeing it appears to think it is hidden/off while on the secondary monitor.  As in when moving to the right off the primary it thinks it is gone?
And also the icon in the bar does work sometimes and not others for closing, <del>can't determine which conditions, however.</del>
Button works for open and close after startup - for open only after unlock.  Hotkey works as expected under both conditions.

**Comment by trailjeep** [comment]
Commented on github issue thread.

**Comment by lonetwin** [comment]
@kaer Thanks ! I applied the change and tested by locking/unlocking my dual monitor setup and the reported issue seems to be fixed. I haven't tried logout/login or startup yet. Unlike what @trailjeep is reporting tho', the taskbar icon seems to work well for me (ie: both open and close operations work) after an unlock.

Thanks again for the fix. I will report back if I notice anything unusual on login later.

**Comment by kaer** [comment]
Trailjeep to fix it properly I'll need to have the same context of you, in this case dual screen, at the moment I don't two screens, but later I'll take another monitor to test it, already know how to fix it, but is necessary to test this behavior first.

**Comment by kaer** [comment]
Lonetwin thanks by helping improving this extension!! 
Please continue sending issues and features request.

**Comment by trailjeep** [comment]
Understood.  Hey, it's not annoying enough for me not to use it - I really find this extension useful!

**Comment by kaer** [comment]
Today I tested the extension in dual screen and saw the bug, there is no other way to fix it with horizontal sliding, the solution I found was to change the orientation of sliding when more than one monitor is active.

**Comment by lonetwin** [comment]
Hi @kaer 

I just updated to the latest master (commit id 4011881) and unfortunately I noticed a new problem with your latest fix for this issue as referenced in you last comment.

You see I had turned off the option to 'Enable reveal animation'. With this turned off and on a dual monitor setup, the calc dialog doesn't show up. Note that with the option turned off and **without** the dual monitor it works just as expected.

Like I said earlier, I don't know much about g-s-extension coding practices but to be honest, I'm fine with keeping the option turned on if that's the only way to have it work consistently on dual monitor setups.

If you think this is a good work-around, you may as well remove that 'Enable reveal animation' customization.  Hope you see this comment as trying to make this nice little tool better and not complaining ;-)

**Comment by kaer** [comment]
I fixed it but didn't tested because don't have a GShell PC with dual screen at the moment, anyway the fix should not have problems.

Thanks!

**Comment by trailjeep** [comment]
Works beautifully now! Thanks.

**Comment by kaer** [comment]
You're welcome!
