### ISSUE TITLE
Don't work in gnome 3.16

### ISSUE THREAD

**Issue by SnouF** [kaer/gnome-shell-extension-modern-calc#6]
I modify the metadata.json and add gome 3.16

<pre>
"shell-version": [
    "3.10", 
    "3.12", 
    "3.14",
    "3.16"
  ], 
</pre>

After this moderncalc return an error

<pre>
Error: Expected type interface for Argument for 'file' but got to type 'String'
</pre>

**Comment by prtuson** [comment]
I also have this problem. After adding gnome 3.16 to json I get the same error.

**Comment by prtuson** [comment]
Works for me, thank you

**Comment by SnouF** [comment]
Also for me ;)
